export {default as Profile} from './Profile';
export {default as ConnectedUsersList} from './ConnectedUsersList';
export {default as OthersFriendsList} from './OthersFriendsList';
// export { default as ProfileGroupsList } from './ProfileGroupsList';
// export { default as ProfilePagesList } from './ProfilePagesList';
export {default as EditProfile} from './EditProfile';
export {default as EditProfileRelationship} from './EditProfileRelationship';
export {default as EditProfileGender} from './EditProfileGender';
export {default as EditProfileDate} from './EditProfileDate';
export {default as Settings} from './Settings';
export {default as ChangeEmail} from './ChangeEmail';
export {default as DeleteAccount} from './DeleteAccount/DeleteAccount';
export {default as DeleteAccountConfirmation} from './DeleteAccount/DeleteAccountConfirmation';
